name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: src/go.mod
          cache: true

      - name: Download deps
        working-directory: ./src
        run: go mod download

      - name: Install Ginkgo CLI
        run: go install github.com/onsi/ginkgo/v2/ginkgo@latest

      - name: Run unit/spec tests in parallel (exclude database)
        run: |
          make test

      - name: Run database tests (serial)
        env:
          TESTCONTAINERS_RYUK_CONTAINER_PRIVILEGED: "true"
        run: |
          make test-db

